{{- if .Values.Secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activemq.fullname" . }}-secrets
  labels:
    app: {{ include "activemq.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
{{- range $key, $val := .Values.Secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}